config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :headhunters
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :job_opportunities do
    resources :job_profiles, only: [:new, :create, :index, :edit] do
      patch :reject
    end
    resources :offers, only: [:new, :create] do
      put '/accept', to: 'offers#accept'
      get '/reject', to: 'offers#review'
      put '/reject', to: 'offers#reject'
    end
  end
  resources :profiles, only: [:show, :edit, :update, :index] do
    resources :comments, only: [:new, :create]
    resources :favorites, only: [:create, :destroy]
  end
  scope '/headhunters' do
    get 'job_opportunities', to: 'job_opportunities#headhunter', as: :headhunter_job_opportunities
    get 'offer', to: 'offers#index', as: :headhunter_offer
  end

  put '/job_opportunities/:id/close', to: 'job_opportunities#close', as: :close_job_opportunity
end

app/models/profile.rb
# frozen_string_literal: true

class Profile < ApplicationRecord
  belongs_to :user
  has_many :job_profiles
  has_many :job_opportunities, through: :job_profiles
  has_many :comments
  has_many :favorites
  has_many :offers
  has_one_attached :avatar

  def completed?
    [full_name,
     social_name,
     date_birth,
     degree,
     description,
     work_experience].map(&:present?).all?
  end
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  before_action :authenticate_user!, only: [:update]
  before_action :find_profile, only: %i[show update edit]
  before_action :set_attributes_for_headhunter, only: :show, if: :headhunter_signed_in?

  def show; end

  def edit; end

  def update
    if @profile.update(profile_params)
      redirect_to @profile
    else
      render :edit
    end
  end

  def index
    @profiles = Profile.all
  end

  private

  def profile_params
    params.require(:profile).permit(:full_name, :social_name, :date_birth, :degree, :description, :work_experience,
                                   :avatar)
  end

  def set_attributes_for_headhunter
    @comments = current_headhunter.comments
    @comment = Comment.new(profile: @profile)
  end

  def find_profile
    @profile = Profile.find(params[:id])
  end
end

app/views/profiles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'share/errors', object: @profile %>
      <%= form_with model: @profile, class: "shadow p-3 mb-3 bg-dark rounded", local: true do |f| %>
        <div class="form-group row">
          <%= f.label :full_name, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :full_name, class: "form-control shadow rounded" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :social_name, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :social_name, class: "form-control shadow rounded" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :date_birth, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.date_field :date_birth, class: "form-control shadow rounded" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :degree, class: "col-2 col-form-label text-light"%>
          <div class="col-10">
            <%= f.text_field :degree, class: "form-control shadow rounded" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :work_experience, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :work_experience, class: "form-control shadow rounded" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :avatar, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.file_field :avatar, class: "form-control shadow rounded" %>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit 'Salvar', class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<h2>Complete o profile</h2>

<%= render 'form' %>

app/views/profiles/index.html.erb
<h1>Candidatos</h1>

<% @profiles.each do |profile|%>
  <%= link_to profile.full_name, profile %>
  <%= profile.degree %>
<% end %>

<% if @profiles.empty?%>
  <p>Nenhum candidato cadastrado</p>
<% end%>

app/views/profiles/show.html.erb
<h2>Detalhes do profile</h2>

<div  style="width:200px; height:auto">
  <%= image_tag(@profile.avatar, class: "rounded mx-auto d-block" )if @profile.avatar.nil? %>
</div>
<%= @profile.full_name %> 

<% if headhunter_signed_in? && current_headhunter.is_job_seeker_favorite?(@profile)%>
  <span id="favorite" class="glyphicon glyphicon-search" aria-hidden="true"></span>
<% end %>
<%= @profile.social_name %>
<%= l @profile.date_birth if @profile.date_birth %>
<%= @profile.degree %>
<%= @profile.description %>
<%= @profile.work_experience %>
<% if user_signed_in?%>
  <% @profile.job_profiles.each do |job_profile|%>
    <%= job_profile.job_opportunity.title %>
    <%= job_profile.feedback %>
  <% end %>
  <% if @profile.job_opportunities.present?%>
    <% @profile.job_opportunities.each do |job_profile| %>
      <p>Participando da vaga: <%= job_profile.title %></p>
    <% end %>
  <% end %>
<% end %>

<% if headhunter_signed_in?%>
  <%= link_to 'Comentar', new_profile_comment_path(@profile) %>
  <% @comments.each do |comment|%>
    <%= comment.message %>
  <% end %>
  <% @profile.job_profiles.each do |job_profile|%>
    <%= job_profile.job_opportunity.title %>
    <%= job_profile.feedback %>
  <% end %>
  <%= link_to 'Favorito', profile_favorites_path(@profile), method: :post %>
<% end %>


<% @profile.offers.order(created_at: :desc).each do |offer| %>
  <%= offer.salary %>
  <%= offer.benefit %>
  <%= offer.role %>
  <%= l offer.begin_date %>
  <% if offer.criado?%>
    <%= link_to 'Aceitar', job_opportunity_offer_accept_path(offer.job_opportunity,offer), method: :put %>
    <%= link_to 'Rejeitar', job_opportunity_offer_reject_path(offer.job_opportunity,offer) %>
  <% else %>
    <p><%= offer.aceito? ? 'Oferta aceita' : 'Oferta rejeitada'%></p>
  <% end %>
<% end %>