config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :headhunters
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :job_opportunities do
    resources :job_profiles, only: [:new, :create, :index, :edit] do
      patch :reject
    end
    resources :offers, only: [:new, :create] do
      put '/accept', to: 'offers#accept'
      get '/reject', to: 'offers#review'
      put '/reject', to: 'offers#reject'
    end
  end
  resources :profiles, only: [:show, :edit, :update, :index] do
    resources :comments, only: [:new, :create]
    resources :favorites, only: [:create, :destroy]
  end
  scope '/headhunters' do
    get 'job_opportunities', to: 'job_opportunities#headhunter', as: :headhunter_job_opportunities
    get 'offer', to: 'offers#index', as: :headhunter_offer
  end

  put '/job_opportunities/:id/close', to: 'job_opportunities#close', as: :close_job_opportunity
end

app/views/share/_errors.html.erb
<% if object.errors.any?%>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <% object.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  </div>
<% end %>

app/views/share/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'VDE', root_path, class: "navbar-brand", id: 'logo' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Registrar Recrutador', new_headhunter_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
         <li class="nav-item">  
          <%= link_to 'Vagas', job_opportunities_path, class: "nav-link" %>
         </li> 
          <li class="nav-item">  
            <%= link_to 'Registrar Usuário', new_user_registration_path, class: "nav-link",id: 'User'%>
          </li>
          <li class="nav-item">  
            <% if headhunter_signed_in? %>
              <%= link_to 'Sair', destroy_headhunter_session_path, method: :delete, class: "nav-link"%>
              <%= link_to 'Minhas Vagas', headhunter_job_opportunities_path, class: "nav-link"%>
              <%= link_to 'Candidatos', profiles_path, class: "nav-link"%>
              <%= link_to 'Propostas', headhunter_offer_path, class: "nav-link"%>
            <% else %>
              <%= link_to 'Entrar como Recrutador', new_headhunter_session_path, class: "nav-link"%>
            <% end %>
          </li>
          <li class="nav-item">  
            <% if user_signed_in? %>
              <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: "nav-link"%>
              <%= link_to current_user.email, profile_path(current_user.profile), class: "nav-link"%>
            <% else %>
              <%= link_to 'Entrar como Usuário', new_user_session_path, class: "nav-link"%>
            <% end %>
          </li>
      </li>
    </ul>
    
  </div>
</nav>