config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :headhunters
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :job_opportunities do
    resources :job_profiles, only: [:new, :create, :index, :edit] do
      patch :reject
    end
    resources :offers, only: [:new, :create] do
      put '/accept', to: 'offers#accept'
      get '/reject', to: 'offers#review'
      put '/reject', to: 'offers#reject'
    end
  end
  resources :profiles, only: [:show, :edit, :update, :index] do
    resources :comments, only: [:new, :create]
    resources :favorites, only: [:create, :destroy]
  end
  scope '/headhunters' do
    get 'job_opportunities', to: 'job_opportunities#headhunter', as: :headhunter_job_opportunities
    get 'offer', to: 'offers#index', as: :headhunter_offer
  end

  put '/job_opportunities/:id/close', to: 'job_opportunities#close', as: :close_job_opportunity
end

app/models/job_opportunity.rb
# frozen_string_literal: true

class JobOpportunity < ApplicationRecord
  belongs_to :headhunter
  has_many :job_profiles
  has_one :offer
  has_many :profiles, through: :job_profiles
  validates :title, :description, :skills, :salary, :job_level, :end_data, :location, presence: true
  validates :salary, numericality: { greater_than: 0 }
end

app/controllers/job_opportunities_controller.rb
# frozen_string_literal: true

class JobOpportunitiesController < ApplicationController
  before_action :authenticate_headhunter_and_user, only: %i[show index]
  before_action :authenticate_headhunter!, except: %i[show index]
  before_action :set_job_opportunity, only: %i[edit update destroy show close]

  def headhunter
    @job_opportunities = current_headhunter.job_opportunities
    render :index
  end

  def index
    @job_opportunities = JobOpportunity.all
  end

  def show; end

  def new
    @job_opportunity = JobOpportunity.new
  end

  def create
    @job_opportunity = JobOpportunity.new(job_opportunity_params.merge(headhunter: current_headhunter))

    if @job_opportunity.save
      redirect_to @job_opportunity
    else

      render :new
    end
  end

  def edit; end

  def update
    if @job_opportunity.update(job_opportunity_params)
      redirect_to @job_opportunity
    else
      @headhunters = Headhunter.all
      render :edit
    end
  end

  def destroy
    @job_opportunity.destroy

    redirect_to job_opportunities_path
  end

  def close
    @job_opportunity.update(closed: true)
    flash[:notice] = 'Vaga fechada'
    redirect_to @job_opportunity
  end

  private

  def job_opportunity_params
    params.require(:job_opportunity).permit(:title, :description, :skills, :salary, :job_level, :end_data, :location)
  end

  def set_job_opportunity
    @job_opportunity = JobOpportunity.find(params[:id])
  end

  def authenticate_headhunter_and_user
    authenticate_user! unless headhunter_signed_in? || user_signed_in?
  end
end

app/views/job_opportunities/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'share/errors', object: @job_opportunity %>
      <%= form_with model: @job_opportunity, class: "shadow p-3 mb-3 bg-dark rounded", local: true do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :skills, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :skills, class: "form-control shadow rounded" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :salary, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.number_field :salary, class: "form-control shadow rounded" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :job_level, class: "col-2 col-form-label text-light"%>
          <div class="col-10">
            <%= f.text_field :job_level, class: "form-control shadow rounded" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :end_data, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.date_field :end_data, class: "form-control shadow rounded" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :location, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :location, class: "form-control shadow rounded" %>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit 'Enviar', class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/job_opportunities/edit.html.erb
<h2 class="text-center">Editar vaga</h2>

<%= render 'form' %>

app/views/job_opportunities/index.html.erb
<h2 class="text-center">Vagas</h2>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <% if @job_opportunities.empty?%>
          <p class="alert-heading text-center">Nenhuma vaga criada</p>
        <% else %>
          <% @job_opportunities.each do |job_opportunity| %>
            <% if !job_opportunity.closed%>
              <div class="card">
                <div class="card-header">
                  <%= link_to job_opportunity.title, job_opportunity %>
                </div>
                <div class="card-body">
                  <%= job_opportunity.description %>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="form-group row justify-content-center">
  <%= link_to 'Cadastrar vaga', new_job_opportunity_path, class: "btn btn-outline-dark btn-lg"%>
</div>

app/views/job_opportunities/new.html.erb
<h2 class="text-center">Cadastrar nova vaga</h2>

<%= render 'form' %>

app/views/job_opportunities/show.html.erb
<h2 class="text-center">Detalhes</h2>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          <div class="card-header font-italic">
            <%= @job_opportunity.title %>
          </div>
          <div class="card-body">
            <%= @job_opportunity.description %>
          </div>
          <div class="card-body">
            <%= @job_opportunity.skills %>
          </div>
           <div class="card-body">
            <%= JobOpportunity.human_attribute_name(:salary) %>: <%= @job_opportunity.salary %>
          </div>
           <div class="card-body">
            <%= @job_opportunity.job_level %>
          </div>
           <div class="card-body">
            <%= l @job_opportunity.end_data %>
          </div>
           <div class="card-body">
            <%= JobOpportunity.human_attribute_name(:location) %>: <%= @job_opportunity.location %>
          </div>
           <div class="card-body">
            <%= @job_opportunity.headhunter.email %>
          </div>
          
          <% if user_signed_in?%>
            <% if !@job_opportunity.closed?%>
              <%= link_to 'Inscrever', job_opportunity_job_profiles_path(@job_opportunity), method: :post%>  
            <% end %>
            
          <% else%>
            <% if !@job_opportunity.closed?%>
              <%= link_to 'Fechar', close_job_opportunity_path(@job_opportunity), method: :put %>
              <%= link_to 'Editar', edit_job_opportunity_path(@job_opportunity), class: "btn btn-outline-dark btn-lg" %>
            <% end %>
            <%= link_to 'Candidatos da Vaga', job_opportunity_job_profiles_path(@job_opportunity) %>
            
            <%= link_to 'Apagar', job_opportunity_path(@job_opportunity), method: :delete, data: {confirm: 'Você tem certeza'}, class: "btn btn-outline-dark btn-lg" %>
          <% end %>
          <%= link_to 'Voltar', job_opportunities_path, class: "btn btn-outline-dark btn-lg" %>
        </div>
      </div>
    </div>
  </div>
</div>